version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../elmobil/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./img/:/temp_data/img/
      - ./data.sqlite3:/temp_data/data.sqlite3
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - media:/static/media
    depends_on:
      - backend