# Generated by Django 5.0.3 on 2025-04-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="preceding_car",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_model",
                to="catalog.car",
                verbose_name="Предыдущая модель",
            ),
        ),
    ]
