# Generated by Django 5.0.3 on 2024-04-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecar',
            name='image',
            field=models.ImageField(upload_to='car_images/', verbose_name='Фото'),
        ),
    ]
