# Generated by Django 3.2.20 on 2024-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charging',
            name='port_location_2',
        ),
        migrations.RemoveField(
            model_name='charging',
            name='port_location',
        ),
        migrations.AddField(
            model_name='charging',
            name='port_location',
            field=models.ManyToManyField(blank=True, null=True, related_name='charging', to='catalog.PortLocation', verbose_name='Расположение порта'),
        ),
    ]
