# Generated by Django 3.2.20 on 2023-10-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.battery', verbose_name='Батарея'),
        ),
        migrations.AlterField(
            model_name='car',
            name='charging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.charging', verbose_name='Зарядка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='charging_fast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_fast_charge', to='catalog.charging', verbose_name='Быстрая зарядка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dimensions_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.dimensionsweight', verbose_name='Безопасность'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='miscellaneous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.miscellaneous', verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='car',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.performance', verbose_name='Производительность'),
        ),
        migrations.AlterField(
            model_name='car',
            name='real_range_estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.rangeestimation', verbose_name='Оценка реального диапазона'),
        ),
    ]
