# Generated by Django 3.2.20 on 2024-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20240322_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging',
            name='port_location',
            field=models.ManyToManyField(blank=True, related_name='charging', to='catalog.PortLocation', verbose_name='Расположение порта'),
        ),
    ]
