# Generated by Django 5.0.3 on 2025-05-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_car_preceding_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="slug",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=256,
                null=True,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
