# Generated by Django 3.2.20 on 2023-10-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20231009_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portlocation',
            options={'verbose_name': 'расположение порта', 'verbose_name_plural': 'Расположение порта'},
        ),
        migrations.AlterField(
            model_name='portlocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_location_location', to='catalog.side', verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='portlocation',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_location_side', to='catalog.side', verbose_name='Сторона'),
        ),
    ]
