# Generated by Django 5.0.3 on 2024-04-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_imagecar_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'default_related_name': 'car', 'verbose_name': 'электромобиль', 'verbose_name_plural': 'Электромобили'},
        ),
        migrations.AlterField(
            model_name='imagecar',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
