# Generated by Django 3.2.20 on 2024-03-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_charging_port_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='car_images', verbose_name='Фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ManyToManyField(related_name='cars', to='catalog.Image'),
        ),
    ]
