# Generated by Django 3.2.20 on 2024-03-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20240322_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageCar',
        ),
    ]
