# Generated by Django 3.2.20 on 2023-10-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20231009_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_until',
            field=models.IntegerField(default=None, null=True, verbose_name='Выпускался до'),
        ),
    ]
