# Generated by Django 5.0.3 on 2024-03-22 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_image_car_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battery',
            name='architecture',
            field=models.ForeignKey(blank=True, help_text='V', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.architecturebattery', verbose_name='Напряжение'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='battery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.batterytype', verbose_name='Тип батареи'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='cathode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cathode', verbose_name='Катод'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='nominal_voltage',
            field=models.ForeignKey(blank=True, help_text='В', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.nominalvoltage', verbose_name='Вольтаж'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='pack_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.packconfiguration', verbose_name='Конфигурация'),
        ),
        migrations.AlterField(
            model_name='car',
            name='battery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.battery', verbose_name='Батарея'),
        ),
        migrations.AlterField(
            model_name='car',
            name='charging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.charging', verbose_name='Зарядка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dimensions_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.dimensionsweight', verbose_name='Габариты и вес'),
        ),
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.ManyToManyField(to='catalog.imagecar'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='miscellaneous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.miscellaneous', verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='car',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.performance', verbose_name='Производительность'),
        ),
        migrations.AlterField(
            model_name='car',
            name='real_range_estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.rangeestimation', verbose_name='Оценка реального диапазона'),
        ),
        migrations.AlterField(
            model_name='charging',
            name='port_location',
            field=models.ManyToManyField(blank=True, to='catalog.portlocation', verbose_name='Расположение порта'),
        ),
        migrations.AlterField(
            model_name='charging',
            name='type_electric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.typeelectric', verbose_name='Тип электричества'),
        ),
        migrations.AlterField(
            model_name='charging',
            name='type_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.portcharge', verbose_name='Тип порта'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='car_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.carbody', verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.platform', verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.segment', verbose_name='Сегмент'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='acceleration_to_100',
            field=models.ForeignKey(blank=True, help_text='с.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.accelerationto', verbose_name='Разгон до 100км/ч'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.drive', verbose_name='Привод'),
        ),
    ]
