# Generated by Django 3.2.20 on 2023-10-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
    ]
