# Generated by Django 3.2.20 on 2023-10-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_manufacturer_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battery',
            old_name='useable_capacity',
            new_name='useble_capacity',
        ),
    ]
