# Generated by Django 3.2.20 on 2023-10-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_useable_capacity_battery_useble_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='acceleration_to_100',
            field=models.ForeignKey(blank=True, help_text='с.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance', to='catalog.accelerationto', verbose_name='Разгон до 100км/ч'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='acceleration_to_200',
            field=models.ForeignKey(blank=True, help_text='с.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_to_200', to='catalog.accelerationto', verbose_name='Разгон до 200км/ч'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='electric_range',
            field=models.IntegerField(help_text='Км', verbose_name='Запас хода'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='top_speed',
            field=models.IntegerField(help_text='Км/ч', verbose_name='Максимальная скорость'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='total_power',
            field=models.IntegerField(help_text='кВт', verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='total_torque',
            field=models.IntegerField(help_text='Нм', verbose_name='Крутящий момент'),
        ),
    ]
