# Generated by Django 3.2.20 on 2023-10-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20231028_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battery',
            old_name='useble_capacity',
            new_name='usable_capacity',
        ),
    ]
