# Generated by Django 3.2.20 on 2023-10-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_useble_capacity_battery_usable_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battery',
            options={'default_related_name': 'battery', 'verbose_name': 'батарея', 'verbose_name_plural': 'Батарея'},
        ),
        migrations.RenameField(
            model_name='nominalvoltage',
            old_name='value_voltage',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='packconfiguration',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Значение'),
        ),
    ]
