# Generated by Django 3.2.20 on 2023-10-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20231028_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensionsweight',
            options={'verbose_name': 'размер и вес', 'verbose_name_plural': 'Габариты и Вес'},
        ),
        migrations.AddField(
            model_name='car',
            name='next_car',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_model', to='catalog.car', verbose_name='Предыдущая модель'),
        ),
        migrations.AddField(
            model_name='car',
            name='preceding_car',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preceding_model', to='catalog.car', verbose_name='Предыдущая модель'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='architecture',
            field=models.ForeignKey(blank=True, help_text='V', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery', to='catalog.architecturebattery', verbose_name='Напряжение'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='nominal_capacity',
            field=models.DecimalField(decimal_places=2, help_text='кВт⋅ч', max_digits=10, verbose_name='Номинальная мощность'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='nominal_voltage',
            field=models.ForeignKey(blank=True, help_text='В', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery', to='catalog.nominalvoltage', verbose_name='Вольтаж'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='number_of_cells',
            field=models.IntegerField(blank=True, help_text='шт.', verbose_name='Количество ячеек'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='usable_capacity',
            field=models.DecimalField(decimal_places=2, help_text='кВт⋅ч', max_digits=10, verbose_name='Полезная мощность'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dimensions_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.dimensionsweight', verbose_name='Габариты и вес'),
        ),
        migrations.AlterField(
            model_name='charging',
            name='charge_power',
            field=models.DecimalField(decimal_places=2, help_text='кВт⋅ч', max_digits=10, verbose_name='Мощность зарядки'),
        ),
        migrations.AlterField(
            model_name='charging',
            name='charge_speed',
            field=models.IntegerField(blank=True, help_text='км/ч', verbose_name='Скорость зарядки'),
        ),
        migrations.AlterField(
            model_name='charging',
            name='charge_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время до полной зарядки'),
        ),
        migrations.AlterField(
            model_name='dimensionsweight',
            name='cargo_volume',
            field=models.IntegerField(help_text='л.', null=True, verbose_name='Объем багажника'),
        ),
        migrations.AlterField(
            model_name='dimensionsweight',
            name='cargo_volume_frunk',
            field=models.IntegerField(help_text='л.', null=True, verbose_name='Объем переднего багажника'),
        ),
        migrations.AlterField(
            model_name='dimensionsweight',
            name='gross_weight',
            field=models.IntegerField(help_text='кг.', null=True, verbose_name='Полная масса'),
        ),
        migrations.AlterField(
            model_name='dimensionsweight',
            name='height',
            field=models.IntegerField(help_text='мм', null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='dimensionsweight',
            name='length',
            field=models.IntegerField(help_text='мм', null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='dimensionsweight',
            name='payload',
            field=models.IntegerField(help_text='кг.', null=True, verbose_name='Грузоподъемность'),
        ),
        migrations.AlterField(
            model_name='dimensionsweight',
            name='weight_unladen',
            field=models.IntegerField(help_text='кг.', null=True, verbose_name='Вес без нагрузки'),
        ),
        migrations.AlterField(
            model_name='dimensionsweight',
            name='wheelbase',
            field=models.IntegerField(help_text='мм', null=True, verbose_name='Колесная база'),
        ),
        migrations.AlterField(
            model_name='dimensionsweight',
            name='width',
            field=models.IntegerField(help_text='мм', null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='dimensionsweight',
            name='width_with_mirrors',
            field=models.IntegerField(help_text='мм', null=True, verbose_name='Ширина с зеркалами'),
        ),
    ]
