# Generated by Django 3.2.20 on 2023-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20231030_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miscellaneous',
            options={'default_related_name': 'miscellaneous', 'verbose_name': 'дополнительно', 'verbose_name_plural': 'Разное'},
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='car_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='charging',
            name='charge_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время зарядки (до 80%)'),
        ),
        migrations.AlterField(
            model_name='rangeestimation',
            name='city_cold',
            field=models.IntegerField(help_text='км.', verbose_name='Город в холодную погоду'),
        ),
        migrations.AlterField(
            model_name='rangeestimation',
            name='city_mild',
            field=models.IntegerField(help_text='км.', verbose_name='Город в теплую погоду'),
        ),
        migrations.AlterField(
            model_name='rangeestimation',
            name='combined_cold',
            field=models.IntegerField(help_text='км.', verbose_name='Смешанный в холодную погоду'),
        ),
        migrations.AlterField(
            model_name='rangeestimation',
            name='combined_mild',
            field=models.IntegerField(help_text='км.', verbose_name='Смешанный в теплую погоду'),
        ),
        migrations.AlterField(
            model_name='rangeestimation',
            name='highway_cold',
            field=models.IntegerField(help_text='км.', verbose_name='Трасса в холодную погоду'),
        ),
        migrations.AlterField(
            model_name='rangeestimation',
            name='highway_mild',
            field=models.IntegerField(help_text='км.', verbose_name='Трасса в теплую погоду'),
        ),
    ]
