# Generated by Django 3.2.20 on 2023-10-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20231030_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging',
            name='charge_time',
            field=models.TimeField(blank=True, help_text='ч:м:с', null=True, verbose_name='Время зарядки (до 80%)'),
        ),
    ]
