# Generated by Django 3.2.20 on 2023-09-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('post_url', models.URLField(default=models.CharField(max_length=56), max_length=75)),
                ('date_of_create', models.DateField(auto_now_add=True)),
                ('date_of_change', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('views_count', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(default='autor', on_delete=django.db.models.deletion.PROTECT, to='blog.autor')),
                ('category', models.ManyToManyField(to='blog.Category')),
                ('tags', models.ManyToManyField(to='blog.Tags')),
            ],
        ),
    ]
