# Generated by Django 5.0.3 on 2024-03-25 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('post_slug', models.CharField(default=models.CharField(max_length=75), max_length=75)),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('date_of_change', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('views_count', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(default='autor', on_delete=django.db.models.deletion.PROTECT, to='blog.autor')),
                ('category', models.ManyToManyField(default=None, to='blog.category')),
                ('tags', models.ManyToManyField(default=None, to='blog.tags')),
            ],
        ),
    ]
