# Generated by Django 3.2.20 on 2023-09-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_url',
        ),
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.CharField(default=models.CharField(max_length=56), max_length=75),
        ),
    ]
